CREATE TABLE `alveo_export` (
                                `account` int(11) NOT NULL,
                                `dashmin` int(11) NOT NULL,
                                `account_created_on` date DEFAULT NULL,
                                `account_label` varchar(50) DEFAULT NULL,
                                `first_name` varchar(50) DEFAULT NULL,
                                `last_name` varchar(50) DEFAULT NULL,
                                `phone` varchar(45) DEFAULT NULL,
                                `email` varchar(100) DEFAULT NULL,
                                `start_balance` decimal(10,0) DEFAULT NULL,
                                `current_balance` decimal(10,0) DEFAULT NULL,
                                `highest_balance` decimal(10,0) DEFAULT NULL,
                                `lowest_balance` decimal(10,0) DEFAULT NULL,
                                `daily_return` decimal(10,0) DEFAULT NULL,
                                `num_trades` int(11) DEFAULT NULL,
                                `num_win_trades` int(11) DEFAULT NULL,
                                `num_loss_trades` int(11) DEFAULT NULL,
                                `amt_win_trades` decimal(10,0) DEFAULT NULL,
                                `amt_loss_trades` decimal(10,0) DEFAULT NULL,
                                `avg_win_trade_amt` decimal(10,0) DEFAULT NULL,
                                `avg_loss_trade_amt` decimal(10,0) DEFAULT NULL,
                                `expectancy` decimal(10,0) DEFAULT NULL,
                                `sharpe_ratio` double DEFAULT NULL,
                                `report_date` date NOT NULL,
                                `processing_date` date DEFAULT NULL,
                                PRIMARY KEY (`account`,`report_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;
